# Generated by Django 3.2.8 on 2021-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=150)),
                ('rating', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'User Profile Comments',
            },
        ),
    ]
