# Generated by Django 3.2.8 on 2021-11-14 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofilecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilecomment',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
