# Generated by Django 3.2.8 on 2021-11-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofilecomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilecomment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
