# Generated by Django 3.2.8 on 2021-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofilecomment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilecomment',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
