# Generated by Django 3.2.8 on 2021-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_rename_plants_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='discount',
        ),
        migrations.AddField(
            model_name='plant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
            preserve_default=False,
        ),
    ]
