# Generated by Django 3.2.8 on 2021-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20211031_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
